tasks:
  - init: sudo apt install gcc-arm-none-eabi && export PICO_SDK_PATH="/workspace/PicoOnGitpod/pico/pico-sdk" mkdir build && cd build && cmake ..

vscode:
  extensions:
    - ms-vscode.cmake-tools
    - twxs.cmake
